# Generated by Django 2.2 on 2021-04-07 11:51

from django.db import migrations, models
import django.db.models.deletion
import tracking.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('imo_number', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[tracking.models.validate_imo_number])),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(max_length=20)),
                ('latitude', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.Ship')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
